parameters:
#    cron_cron.example.class: Cron\CronBundle\Example
  #my_user_provider.class: Cron\CronBundle\Service\CronUserProvider

services:
#    cron_cron.example:
#        class: %cron_cron.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    #my_user_provider:
        #class: "%my_user_provider.class%"
        #arguments: []
