Cron\CronBundle\Entity\Question:
  properties:
    text:
      - NotBlank: ~
    category:
      - NotBlank: ~

Cron\CronBundle\Entity\User:
  properties:
    username:
      - NotBlank:   { message: "поле не заполнено" }
      - Email:      { message: "некорректное заполнение" }
    nick:
      - NotBlank:   { message: "поле не заполнено" }
    gender:
      - NotBlank:   { message: "укажите ваш пол" }
    country:
      - NotBlank:   { message: "поле не заполнено" }
    state:
      - NotBlank:   { message: "поле не заполнено" }
    city:
      - NotBlank:   { message: "поле не заполнено" }
    agreement:
      - NotBlank:   { message: "вы не ознакомились с пользовательским соглашением" }