Cron\CronBundle\Entity\Question:
  properties:
    text:
      - NotBlank: ~
    category:
      - NotBlank: ~

Cron\CronBundle\Entity\User:
  properties:
    username:
      - NotBlank: ~
    country:
      - NotBlank: ~
    state:
      #- NotBlank: ~
    city:
      #- NotBlank: ~