cron_cron:
    resource: "@CronCronBundle/Resources/config/routing.yml"
    prefix:   /

index:
  pattern:  /
  defaults: { _controller: CronCronBundle:Main:index }

category:
  pattern: /category
  defaults: { _controller: CronCronBundle:Main:category }

rush:
  pattern: /rush
  defaults: { _controller: CronCronBundle:Main:rush }

disk:
  pattern: /disk
  defaults: { _controller: CronCronBundle:Main:disk }

register:
  pattern: /register
  defaults: { _controller: CronCronBundle:Main:register }

regconf:
  pattern: /regconf
  defaults: { _controller: CronCronBundle:Main:regconf }

# Ajax routes

getStates:
  pattern:  /ajax/getStates
  defaults: { _controller: CronCronBundle:Ajax:getStates }

getCities:
  pattern:  /ajax/getCities
  defaults: { _controller: CronCronBundle:Ajax:getCities }

getUpdate:
  pattern:  /ajax/getUpdate
  defaults: { _controller: CronCronBundle:Ajax:getUpdate }

delQuestion:
  pattern:  /ajax/delQuestion
  defaults: { _controller: CronCronBundle:Ajax:delQuestion }

likeItem:
  pattern:  /ajax/likeItem
  defaults: { _controller: CronCronBundle:Ajax:likeItem }

postAnswer:
  pattern:  /ajax/postAnswer
  defaults: { _controller: CronCronBundle:Ajax:postAnswer }

uploadFile:
  pattern:  /ajax/uploadFile
  defaults: { _controller: CronCronBundle:Ajax:uploadFile }

# Security routes

login:
    pattern:  /login
    defaults: { _controller: CronCronBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
