cron_cron:
    resource: "@CronCronBundle/Resources/config/routing.yml"
    prefix:   /

index:
  pattern:  /
  defaults: { _controller: CronCronBundle:Main:index }

category:
  pattern: /category
  defaults: { _controller: CronCronBundle:Main:category }

rush:
  pattern: /rush
  defaults: { _controller: CronCronBundle:Main:rush }

# Ajax routes

getStates:
  pattern:  /ajax/getStates
  defaults: { _controller: CronCronBundle:Ajax:getStates }

getCities:
  pattern:  /ajax/getCities
  defaults: { _controller: CronCronBundle:Ajax:getCities }

getUpdate:
  pattern:  /ajax/getUpdate
  defaults: { _controller: CronCronBundle:Ajax:getUpdate }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
