cron_cron:
    resource: "@CronCronBundle/Resources/config/routing.yml"
    prefix:   /

index:
  pattern:  /
  defaults: { _controller: CronCronBundle:Main:index }

category:
  pattern: /category/{category_id}
  defaults: { _controller: CronCronBundle:Main:category, "category_id": "" }

rush:
  pattern: /rush
  defaults: { _controller: CronCronBundle:Main:rush }

disk:
  pattern: /disk/{file_hash}
  defaults: { _controller: CronCronBundle:Main:disk, "file_hash": "" }

settings:
  pattern: /settings
  defaults: { _controller: CronCronBundle:Main:settings }

articles:
  pattern: /articles/{category_id}/{article_id}
  defaults: { _controller: CronCronBundle:Main:articles, "category_id": "", "article_id": "" }

notes:
  pattern: /notes/{location}
  defaults: { _controller: CronCronBundle:Main:notes}

locale:
  pattern: /locale/{locale}
  defaults: { _controller: CronCronBundle:Main:locale }
#disk:
  #pattern: /disk/
  #defaults: { _controller: CronCronBundle:Main:disk }

register:
  pattern: /register
  defaults: { _controller: CronCronBundle:Main:register }

regconf:
  pattern: /regconf
  defaults: { _controller: CronCronBundle:Main:regconf }

# Ajax routes

getStates:
  pattern:  /ajax/getStates
  defaults: { _controller: CronCronBundle:Ajax:getStates }

getCities:
  pattern:  /ajax/getCities
  defaults: { _controller: CronCronBundle:Ajax:getCities }

getUpdate:
  pattern:  /ajax/getUpdate
  defaults: { _controller: CronCronBundle:Ajax:getUpdate }

delQuestion:
  pattern:  /ajax/delQuestion
  defaults: { _controller: CronCronBundle:Ajax:delQuestion }

likeItem:
  pattern:  /ajax/likeItem
  defaults: { _controller: CronCronBundle:Ajax:likeItem }

spamItem:
  pattern:  /ajax/spamItem
  defaults: { _controller: CronCronBundle:Ajax:spamItem }

postAnswer:
  pattern:  /ajax/postAnswer
  defaults: { _controller: CronCronBundle:Ajax:postAnswer }

uploadFile:
  pattern:  /ajax/uploadFile
  defaults: { _controller: CronCronBundle:Ajax:uploadFile }

deleteFile:
  pattern:  /ajax/deleteFile
  defaults: { _controller: CronCronBundle:Ajax:deleteFile }

getLastFile:
  pattern:  /ajax/getLastFile
  defaults: { _controller: CronCronBundle:Ajax:getLastFile }

updateFilesize:
  pattern:  /ajax/updateFilesize
  defaults: { _controller: CronCronBundle:Ajax:updateFilesize }

saveSettings:
  pattern:  /ajax/saveSettings
  defaults: { _controller: CronCronBundle:Ajax:saveSettings }

newUserLink:
  pattern:  /ajax/newUserLink
  defaults: { _controller: CronCronBundle:Ajax:newUserLink }

getUserLinks:
  pattern:  /ajax/getUserLinks
  defaults: { _controller: CronCronBundle:Ajax:getUserLinks }

repostQuestion:
  pattern:  /ajax/repostQuestion
  defaults: { _controller: CronCronBundle:Ajax:repostQuestion }

bookmarkArticle:
  pattern:  /ajax/bookmarkArticle
  defaults: { _controller: CronCronBundle:Ajax:bookmarkArticle }

unbookmarkArticle:
  pattern:  /ajax/unbookmarkArticle
  defaults: { _controller: CronCronBundle:Ajax:unbookmarkArticle }

loadNotepad:
  pattern:  /ajax/loadNotepad
  defaults: { _controller: CronCronBundle:Ajax:loadNotepad }

updateNotepad:
  pattern:  /ajax/updateNotepad
  defaults: { _controller: CronCronBundle:Ajax:updateNotepad }


# Chat routes

loadChat:
  pattern:  /chat/loadChat
  defaults: { _controller: CronCronBundle:Chat:loadChat }

updateChat:
  pattern:  /chat/updateChat
  defaults: { _controller: CronCronBundle:Chat:updateChat }

getSrvMsg:
  pattern:  /chat/getSrvMsg
  defaults: { _controller: CronCronBundle:Chat:getSrvMsg }

getDialogList:
  pattern:  /chat/getDialogList
  defaults: { _controller: CronCronBundle:Chat:getDialogList }

getInviteList:
  pattern:  /chat/getInviteList
  defaults: { _controller: CronCronBundle:Chat:getInviteList }
  
getDialogMsgs:
  pattern:  /chat/getDialogMsgs
  defaults: { _controller: CronCronBundle:Chat:getDialogMsgs }

getChatMsgs:
  pattern:  /chat/getChatMsgs
  defaults: { _controller: CronCronBundle:Chat:getChatMsgs }

getMyChat:
  pattern:  /chat/getMyChat
  defaults: { _controller: CronCronBundle:Chat:getMyChat }

getIncomeChats:
  pattern:  /chat/getIncomeChats
  defaults: { _controller: CronCronBundle:Chat:getIncomeChats }

sendDialogMsg:
  pattern:  /chat/sendDialogMsg
  defaults: { _controller: CronCronBundle:Chat:sendDialogMsg }

sendChatMsg:
  pattern:  /chat/sendChatMsg
  defaults: { _controller: CronCronBundle:Chat:sendChatMsg }

readDialogMsgs:
  pattern:  /chat/readDialogMsgs
  defaults: { _controller: CronCronBundle:Chat:readDialogMsgs }

deleteDialog:
  pattern:  /chat/deleteDialog
  defaults: { _controller: CronCronBundle:Chat:deleteDialog }

createDialog:
  pattern:  /chat/createDialog
  defaults: { _controller: CronCronBundle:Chat:createDialog }

openDialog:
  pattern:  /chat/openDialog
  defaults: { _controller: CronCronBundle:Chat:openDialog }

closeDialog:
  pattern:  /chat/closeDialog
  defaults: { _controller: CronCronBundle:Chat:closeDialog }

checkDialogAsSpam:
  pattern:  /chat/checkDialogAsSpam
  defaults: { _controller: CronCronBundle:Chat:checkDialogAsSpam }

acceptChatInvite:
  pattern:  /chat/acceptChatInvite
  defaults: { _controller: CronCronBundle:Chat:acceptChatInvite }

declineChatInvite:
  pattern:  /chat/declineChatInvite
  defaults: { _controller: CronCronBundle:Chat:declineChatInvite }

finishChat:
  pattern:  /chat/finishChat
  defaults: { _controller: CronCronBundle:Chat:finishChat }

leaveChat:
  pattern:  /chat/leaveChat
  defaults: { _controller: CronCronBundle:Chat:leaveChat }

kickUser:
  pattern:  /chat/kickUser
  defaults: { _controller: CronCronBundle:Chat:kickUser }

sendChatInvite:
  pattern:  /chat/sendChatInvite
  defaults: { _controller: CronCronBundle:Chat:sendChatInvite }

# Admin routes

newarticle:
  pattern:  /admin/newarticle
  defaults: { _controller: CronCronBundle:Admin:newarticle }


# Security routes

login:
    pattern:  /login
    defaults: { _controller: CronCronBundle:Security:login }

login_check:
    pattern:  /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
