jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Cron\CronBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #my_user_provider: { class: Cron\CronBundle\Entity\User }#, property: username }
        main:
          #id: my_user_provider #{ class: Cron\CronBundle\Entity\User }
            entity: { class: Cron\CronBundle\Entity\User }
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/ajax, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
