jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Cron\CronBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
#        ROLE_SPAM_CHECKER:       [ROLE_ADMIN, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #my_user_provider: { class: Cron\CronBundle\Entity\User }#, property: username }
        main:
          #id: my_user_provider #{ class: Cron\CronBundle\Entity\User }
            entity: { class: Cron\CronBundle\Entity\User }
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
            logout: true
            security: true
            anonymous: true

    access_control:
        # Админка
#        - { path: ^/admin, roles: ROLE_ADMIN }

        # Кредиты
        - { path: ^/credits, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/pay, roles: IS_AUTHENTICATED_FULLY }
        # Заметки
        - { path: ^/notes, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/ajax/loadNotepad, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ajax/updateNotepad, roles: IS_AUTHENTICATED_FULLY }
        # Ссылки быстрого доступа
        - { path: ^/ajax/newUserLink, roles: IS_AUTHENTICATED_FULLY }
        # Настройки
        - { path: ^/settings, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ajax/saveSettings, roles: IS_AUTHENTICATED_FULLY }
        # Кибердиск
        - { path: ^/disk, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/ajax/uploadFile, roles: IS_AUTHENTICATED_FULLY }
        # Все остальное
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
